### ISSUE TITLE
[124] Add robots.txt to frontity.media to avoid GSC errors

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/cloud#13]
Add robots txt with:
```
User-agent: *
Disallow:
```

---- 

https://frontity.pipedrive.com/deal/54

Site pageviews: **(0.18)**
Extra group sites: **(0)**
Extra group pageviews: **(0)**
Development size: **(2)**
Blocking: **no frontity without it (x10)**
Environment: **production (x3)**
Reusability potential: **everyone (x10)**
Referrer: **yes (x3)**
PRIORITY: **[124]**

**Comment by luisherranz** [comment]
In https://cdn.frontity.media/robots.txt it should appear:
```
User-agent: *
Disallow:
```

**Comment by SantosGuillamot** [comment]
#notify
